// cli1 - Minimal command-line Black Friday program
// Example front-end for command-line use
// Most stripped-down possible input. Give it a
// markdown file and the name of an output HTML file,
// and it generates that HTML file from the markup.

// Example:
// ./cli1 foo.md foo.html
//
package main

import (
	"fmt"
	"github.com/russross/blackfriday"
	"io/ioutil"
	"os"
)


func generateHTML(infile string, outfile string, title string, css string) {
	var input []byte
	var err error
	// Read the markdown file into a byte slice.
	if input, err = ioutil.ReadFile(infile); err != nil {
		fmt.Fprintln(os.Stderr, "Error reading from", infile, ":", err)
		os.Exit(-1)
	}
	// Create an object to do the rendering.
	// Pass it the contents of a title tag, and CSS
	// (which in this case isn't used)
	renderer := blackfriday.HtmlRenderer(blackfriday.HTML_COMPLETE_PAGE,
		title, css)

	// Read the markdown file from the byte slice named
	// input, render to HTML, and write 
	// to a byte slice named output.
	var output []byte
	output = blackfriday.Markdown(input, renderer, 0)

	// Take the rendered HTML and open up a file object.
	var out *os.File
	if out, err = os.Create(outfile); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating %s: %v", outfile, err)
		os.Exit(-1)
	}
	defer out.Close()

	// Take the generated byte slice in output and
	// create an HTML file.
	if _, err = out.Write(output); err != nil {
		fmt.Fprintln(os.Stderr, "Error creating HTML file %v: %v", outfile, err)
		os.Exit(-1)
	}
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr,
		"Please specify 2 filenames: the first is a markdown file, the second is an HTML output file.")
		os.Exit(-1)
	}
	generateHTML(os.Args[1], os.Args[2], "Markdown!", "h1 { color: red; }")

}


